### ISSUE TITLE
Don't have permission to repo to update repo secrets

### ISSUE THREAD

**Issue by Kritner** [OrleansContrib/Orleans.SyncWork#38]
Hey @ReubenBond could you help me out here, or ping someone that would be able to?

My NuGet API key expired and I need to set a new one on the repo, but it doesn't look like I have permission to do so.

This repo's settings page:
![image](https://user-images.githubusercontent.com/8814983/208145547-f667e96a-13ac-4e7e-9c88-e587d7e4bb91.png)

A repo where I have access to secrets:
![image](https://user-images.githubusercontent.com/8814983/208145639-a4b331cb-e304-46ce-bcdf-6d5258b1b9b2.png)

**Comment by ReubenBond** [comment]
Apologies for the delay. Use the organization secret instead of the repository secrete there (`NUGET_KEY` instead of `NUGET_API_KEY`) and it ought to work - I updated it a couple of weeks ago

**Comment by ReubenBond** [comment]
Opened a PR to fix this https://github.com/OrleansContrib/Orleans.SyncWork/pull/39

**Comment by ReubenBond** [comment]
You should also have permission now
