### ISSUE TITLE
WhenGivenLargeNumberOfRequests_SystemShouldNotBecomeOverloaded timeout

### ISSUE THREAD

**Issue by hendrikdevloed** [OrleansContrib/Orleans.SyncWork#44]
**Describe the bug**
All unit tests pass, with the exception of `WhenGivenLargeNumberOfRequests_SystemShouldNotBecomeOverloaded`, which timeouts.

**To Reproduce**

**Reproduction Repository**
Current main branch c19842b25ccc9cc3fe1f9bdeaf405504615e2064

**Expected behavior**
Test should not timeout.

**Screenshots**
``` Orleans.SyncWork.Tests.SyncWorkerTests.WhenGivenLargeNumberOfRequests_SystemShouldNotBecomeOverloaded
   Source: SyncWorkerTests.cs line 55
   Duration: 1.5 min

  Message: 
System.TimeoutException : Response did not arrive on time in 00:00:30 for message: Request [ sys.client/6fe2e63ff303466c97dfee58f690f240]->[S127.0.0.1:44340:0 passwordverifier/8a45d6b4d480457f938cb739266c894a] Orleans.SyncWork.ISyncWorker<TRequest,TResult>Orleans.SyncWork.ISyncWorker<TRequest,TResult>.GetWorkStatus() #16573. 

  Stack Trace: 
ResponseCompletionSource`1.GetResult(Int16 token) line 230
<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
SyncWorkerExtensions.StartWorkAndPollUntilResult[TRequest,TResult](ISyncWorker`2 worker, TRequest request, Int32 msDelayPerStatusPoll) line 52
SyncWorkerTests.WhenGivenLargeNumberOfRequests_SystemShouldNotBecomeOverloaded() line 69
--- End of stack trace from previous location ---
```

**Additional context**
I was looking into SyncWork in order to solve the same timeout error in a spike I'm writing to see if Orleans is feasible for us. The 30s timeout error in my own code occurred when an external call into a grain was causing a lot of work setting up other grains, and eventually the initial call timed out.

I expected that this library would avoid precisely this type of error so I was especially surprised to get it again. Perhaps I'm misinterpreting its purpose?

The test passes in 11.7 seconds when scaled down to `for (var i = 0; i < 400; i++)`. 1000 iterations also complete within the deadline, at 27.1 sec.

**Comment by Kritner** [comment]
What kind of max concurrency are you setting on your `LimitedConcurrencyTaskScheduler`? I noticed that on my M1 mac i need to reduce the amount to get it in a workable state, i'm assuming because of the difference in the two types processors

**Comment by Kritner** [comment]
we're running this sort of code in prod, where we have grains taking in the 10s of minutes, so it *can* work, it could likely take some tweaking of the limited concurrency scheduler to get things right however.

**Comment by hendrikdevloed** [comment]
Thanks for the hint!

(Dell Inc. G3 3590 x64-based PC Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 2592 MHz, 6 cores, 12 logic processors)
I've altered the `GetMaxConcurrentGrainWork` function to return 6 instead of 10.

```csharp
var concurrentWork = 2*Environment.ProcessorCount/3 - 2;
```

"Run until failure" so far passes, before it failed at e.g. the third iteration. I've added some unrelated CPU load and observed iterations taking more than the magical 30 sec timeout, so I guess it will be OK.
```
    Iteration 11)         Duration: 36 sec
    Iteration 10)         Duration: 29.9 sec
    Iteration 9)         Duration: 31.5 sec
    Iteration 8)         Duration: 30.5 sec
    Iteration 7)         Duration: 30.8 sec
    Iteration 6)         Duration: 25.4 sec
    Iteration 5)         Duration: 27.6 sec
    Iteration 4)         Duration: 27 sec
    Iteration 3)         Duration: 27.1 sec
    Iteration 2)         Duration: 27.9 sec
    Iteration 1)         Duration: 24.4 sec
```
