### ISSUE TITLE
Upgrade to Orleans 8

### ISSUE THREAD

**Issue by hendrikdevloed** [OrleansContrib/Orleans.SyncWork#47]
After migrating as many Orleans-related packages to 8.0.0 in my Orleans-based application, a runtime exception was encountered
`Could not load type 'Orleans.Serialization.Codecs.TagDelimitedFieldCodec' from assembly 'Orleans.Serialization'`
with the stack pointing to SyncWork-related code.

This seems similar to https://github.com/OrleansContrib/OrleansDashboard/issues/395 which was alledgedly solved by updating the package to match the Orleans runtime.

I removed the SyncWork nuGet reference and replaced it by a locally compiled version of the SyncWork source code, upgraded its runtime and dependencies to Orleans 8 and the error didn't reoccur.

**Comment by Kritner** [comment]
@hendrikdevloed did you have any desire to put in a PR for this change?  I can try to make time for it sometime soon but can't make any promises :3

**Comment by Kritner** [comment]
lol jk, i think i got things working in #48.  I'll try to take a look at merging this and pushing out a new nuget package for it tomorrow

**Comment by Kritner** [comment]
Package is out there now https://www.nuget.org/packages/Orleans.SyncWork/8.0.3, lmk if any issues
