### ISSUE TITLE
Can ISyncWorker omit imposing IGrainWithGuidKey?

### ISSUE THREAD

**Issue by hendrikdevloed** [OrleansContrib/Orleans.SyncWork#52]
The definition
```csharp
public interface ISyncWorker<in TRequest, TResult> : IGrainWithGuidKey
```
imposes the type of key to a grain. Would it be interesting to omit the grain type from the ISyncWorker, or perhaps basing it on a generic `IGrain` (or `IAddressable`, I'm not quite sure what the proper base would be) instead?
```csharp
public interface ISyncWorker<in TRequest, TResult>: IGrain
```
Testing the modification in the SyncWork repo breaks all grainfactory instances, because there is no type system hint what proper overload to choose.
`GrainFactory.GetGrain<ISyncWorker<TestDelaySuccessRequest, TestDelaySuccessResult>>(Guid.NewGuid());` 

I see some options:
- Have a parallel hierarchy ISyncWorkerWithGuidKey<> etc for each of the Orleans grain types
- Have the user name the implementation explicitly like
```csharp
/// <summary>
/// Represents the contract for a SyncWorker grain verifying a password.
/// </summary>
public interface IPasswordVerifierGrain : IPasswordVerifier, ISyncWorker<PasswordVerifierRequest, PasswordVerifierResult>, IGrainWithGuidKey;
```

What are your thoughts on this?

Kind regards,
Hendrik

**Comment by Kritner** [comment]
> Have the user name the implementation explicitly like
> 
> ```cs
> /// <summary>
> /// Represents the contract for a SyncWorker grain verifying a password.
> /// </summary>
> public interface IPasswordVerifierGrain : IPasswordVerifier, ISyncWorker<PasswordVerifierRequest, PasswordVerifierResult>, IGrainWithGuidKey;
> ```

this sounds like a more desirable approach to me.  Could potentially just have both (original and proposed) implementations and helpers around for an interim step, making the "current" as obsolete.  I think this should be doable w/o introducing a breaking change... hopefully :D

Is this something you want to put in a PR for?
